platform :ios, '8.0'
use_frameworks!

target 'RicicloPV' do
#pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SwiftyJSON', :git => 'https://github.com/IBM-Swift/SwiftyJSON'
pod 'Fabric'
pod 'Crashlytics'
end
