platform :ios, '8.0'
use_frameworks!

target 'ioamopavia' do
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'JLToast', '~> 1.3'
pod "PKHUD"
pod 'SearchableTableView'
pod 'Fabric'
pod 'Crashlytics'
end
